### PR TITLE
feat: Wait for DB connection before launching the app

### PR DESCRIPTION
**Pull request by AllDayAlone**

### CODE REVIEW

**Comment by hovoodd** [comment]
Why would we do that? Any problems accessing the database?

**Comment by AllDayAlone** [comment]
> Why would we do that? Any problems accessing the database?

It's just strange that API starts faster because it's useless without DB. I don't have any real case when it's bad though

**Comment by AllDayAlone** [comment]
@hovoodd should we close this?

**Comment by hovoodd** [comment]
> @hovoodd should we close this?

I think so. You can create an issue for further discussion.

**Pull request closed without merging**
