### PR TITLE
Update user email validation

### PR DESCRIPTION
**Pull request by elena-vlasova**
Disable top level domain validation as client side validator can't check TLD.

### CODE REVIEW

**Review by NesterenkoNikita — APPROVED** [review]

**Comment by hovoodd** [comment]
@elena-vlasova Why did you decide to disable TLD checking on the server? This is normal if the validation on the client is different from the validation on the server

**Comment by elena-vlasova** [comment]
@hovoodd Because I can't show server errors under form fields, now they are shown separately on the top of the form. It would be strange for user to see one message in different places.

**Comment by hovoodd** [comment]
@elena-vlasova What about the `setFields` method?

https://www.antdv.com/components/form/#Coordinated-Controls

```js
this.props.form.setFields({
  user: {
    email: values.email,
    errors: [new Error('Invalid email')],
  },
});
```

**Comment by elena-vlasova** [comment]
@hovoodd Antdv 1 doesn't support Vue 3, so I used antdv 2
https://2x.antdv.com/components/form/
We can wait for this method in version 2 and then refactor forms in vue-starter :) And now close this pr

**Pull request closed without merging**
